import java.util.Scanner;
public class NG_Game {

    /*The fun and easy project “Guess the Number” is a short Java project that allows the user to guess the number generated by the computer & involves the following steps:

The system generates a random number from a given range, say 1 to 100.

The user is prompted to enter their given number in a displayed dialogue box.

The computer then tells if the entered number matches the guesses number or it is higher/lower than the generated number.

The game continues under the user guessing the number.

You can also incorporate further details as:

Limiting the number of attempts.

Adding more rounds.

Displaying score.

Giving points based on the number of attempts.

     */
    public static void guessingNumberGame(){

        // Scanner class

        Scanner sc=new Scanner(System.in);

        //Generate the numbers

        int number =1+(int)(100*Math.random());

        //Give R trials

        int R=5;
        int i,guess;
        System.out.println("A number is chosen"+"between 1 to 100."+"Guess the Number"+"within 5 trials.");

        //Iterate over R trials

        for(i=0;i<R;i++){
            System.out.println("Guess The number:");

            //Tale input for guessing

            guess=sc.nextInt();

            //If the number is guessed

            if(number==guess){
                System.out.println("Congratulation!"+"You guessed the number.");
                break;
            }
            else if(number > guess && i!= R-1){
                System.out.println("The number is "+"greater than"+ guess);
            }
            else if(number < guess && i!= R-1) {
                System.out.println("The number is" + "greater than" + guess);
            }
        }
        if(i == R) {
            System.out.println("You have exhausted"+ "R trials.");
            System.out.println("The number was"+number);
        }
    }
    //Driver Code
public static void main(String arg[]){
        //Function call
    guessingNumberGame();

}
}
